"""
cde_executeWithBestAgent - MCP Tool

🚀 **Execute Task with Best Available Agent** - Intelligent agent orchestration.

Tags: workflow, project, documentation, orchestration, analysis, execution, setup, agents

Auto-generated by MCPToolFilesystemGenerator.
"""



def cde_executeWithBestAgent(
    task_description: str,
    project_path: str = ".",
    preferred_agent: str | None = None,
    require_plan_approval: bool = False,
    timeout: int = 1800,
    context_size: int = 1000,
) -> str:
    """
    🚀 **Execute Task with Best Available Agent** - Intelligent agent orchestration.

    Parameters:
        task_description: str, project_path: str, preferred_agent: str | None, require_plan_approval: bool, timeout: int, context_size: int

    Returns:
        JSON string with result

    Tags: workflow, project, documentation, orchestration, analysis, execution, setup, agents
    """
    # This is a stub - actual implementation in src/mcp_tools/cde_executeWithBestAgent.py
    raise NotImplementedError(
        "Use mcp_tools.cde_executeWithBestAgent for actual implementation"
    )


# Metadata for progressive disclosure
TOOL_METADATA = {
    "name": "cde_executeWithBestAgent",
    "description": "🚀 **Execute Task with Best Available Agent** - Intelligent agent orchestration.",
    "parameters": {
        "task_description": {"name": "task_description", "type": "str"},
        "project_path": {"name": "project_path", "type": "str", "default": "."},
        "preferred_agent": {
            "name": "preferred_agent",
            "type": "str | None",
            "default": null,
        },
        "require_plan_approval": {
            "name": "require_plan_approval",
            "type": "bool",
            "default": false,
        },
        "timeout": {"name": "timeout", "type": "int", "default": 1800},
        "context_size": {"name": "context_size", "type": "int", "default": 1000},
    },
    "tags": [
        "workflow",
        "project",
        "documentation",
        "orchestration",
        "analysis",
        "execution",
        "setup",
        "agents",
    ],
}
