"""
cde_installMcpExtension - MCP Tool

Install MCP-related VS Code extension.

Tags: workflow, project, execution, setup

Auto-generated by MCPToolFilesystemGenerator.
"""


def cde_installMcpExtension(
    ctx: fastmcp.server.context.Context,
    extension_name: str = "mcp-status-bar",
    force: bool = False,
) -> str:
    """
    Install MCP-related VS Code extension.

    Parameters:
        ctx: fastmcp.server.context.Context, extension_name: str, force: bool

    Returns:
        JSON string with result

    Tags: workflow, project, execution, setup
    """
    # This is a stub - actual implementation in src/mcp_tools/cde_installMcpExtension.py
    raise NotImplementedError(
        "Use mcp_tools.cde_installMcpExtension for actual implementation"
    )


# Metadata for progressive disclosure
TOOL_METADATA = {
    "name": "cde_installMcpExtension",
    "description": "Install MCP-related VS Code extension.",
    "parameters": {
        "ctx": {"name": "ctx", "type": "fastmcp.server.context.Context"},
        "extension_name": {
            "name": "extension_name",
            "type": "str",
            "default": "mcp-status-bar",
        },
        "force": {"name": "force", "type": "bool", "default": false},
    },
    "tags": ["workflow", "project", "execution", "setup"],
}
