"""
cde_scanDocumentation - MCP Tool

Scan and analyze documentation structure in a project.

Tags: project, documentation, analysis

Auto-generated by MCPToolFilesystemGenerator.
"""



def cde_scanDocumentation(
    project_path: str = ".", detail_level: str = "summary"
) -> str:
    """
    Scan and analyze documentation structure in a project.

    Parameters:
        project_path: str, detail_level: str

    Returns:
        JSON string with result

    Tags: project, documentation, analysis
    """
    # This is a stub - actual implementation in src/mcp_tools/cde_scanDocumentation.py
    raise NotImplementedError(
        "Use mcp_tools.cde_scanDocumentation for actual implementation"
    )


# Metadata for progressive disclosure
TOOL_METADATA = {
    "name": "cde_scanDocumentation",
    "description": "Scan and analyze documentation structure in a project.",
    "parameters": {
        "project_path": {"name": "project_path", "type": "str", "default": "."},
        "detail_level": {"name": "detail_level", "type": "str", "default": "summary"},
    },
    "tags": ["project", "documentation", "analysis"],
}
