"""
Onboarding MCP Tools.

Tools for project onboarding and document publication.
"""

import json
import logging
from pathlib import Path
from typing import Dict

from fastmcp import Context

from cde_orchestrator.adapters.prompt import PromptAdapter
from cde_orchestrator.adapters.repository.git_adapter import GitAdapter
from cde_orchestrator.application.onboarding import OnboardingUseCase
from cde_orchestrator.application.use_cases.manage_state import ManageStateUseCase

from ._base import tool_handler

logger = logging.getLogger(__name__)

# Initialize services (will be moved to DI container later)
CDE_ROOT = Path(__file__).parent.parent.parent
PROMPT_RECIPES_DIR = CDE_ROOT / ".cde" / "prompts"

prompt_manager = PromptAdapter()


@tool_handler
async def cde_onboardingProject(ctx: Context, manage_state_use_case: ManageStateUseCase) -> str:
    """
    Analyzes project structure and performs onboarding setup.
    ...
    """
    # ... (rest of the function is the same, but uses manage_state_use_case)
    state = manage_state_use_case.load_and_validate_state()
    # ...
    manage_state_use_case.save_state(state)
    # ...

@tool_handler
def cde_publishOnboarding(documents: Dict[str, str], manage_state_use_case: ManageStateUseCase, approve: bool = True) -> str:
    """
    Apply onboarding documents generated by an LLM into the repo.
    ...
    """
    # ... (rest of the function is the same, but uses manage_state_use_case)
    state = manage_state_use_case.load_and_validate_state()
    # ...
    manage_state_use_case.save_state(state)
    # ...
