#!/usr/bin/env python3
"""
Bedrock Setup and Configuration Script

Verifica y configura Bedrock para usar con Claude Code y Aider
"""

import sys
import json
import boto3
from pathlib import Path


def check_aws_credentials():
    """Verificar si las credenciales AWS están configuradas"""
    try:
        session = boto3.Session()
        credentials = session.get_credentials()
        if credentials is None:
            print("❌ NO HAY CREDENCIALES AWS CONFIGURADAS")
            print("\n📋 Configura con: aws configure --profile bedrock")
            return False

        print(f"✅ Credenciales AWS encontradas")
        print(f"   Region: {session.region_name or 'default'}")
        return True
    except Exception as e:
        print(f"❌ Error verificando credenciales: {e}")
        return False


def check_bedrock_access():
    """Verificar acceso a Bedrock"""
    try:
        client = boto3.client('bedrock', region_name='us-east-1')
        response = client.list_foundation_models()

        models = response.get('modelSummaries', [])
        print(f"\n✅ Bedrock accesible")
        print(f"   Modelos disponibles: {len(models)}")

        # Listar modelos de Claude
        claude_models = [m for m in models if 'claude' in m.get('modelId', '').lower()]
        if claude_models:
            print(f"\n   🤖 Modelos Claude disponibles:")
            for model in claude_models:
                print(f"      - {model['modelId']}")

        return True
    except Exception as e:
        print(f"\n❌ Error accediendo a Bedrock: {e}")
        print("\n💡 Asegúrate de:")
        print("   1. Ejecutar: aws configure --profile bedrock")
        print("   2. Ingresar Access Key ID y Secret Access Key")
        print("   3. Region: us-east-1")
        print("   4. Habilitar modelos en Bedrock console: https://console.aws.amazon.com/bedrock/")
        return False


def generate_claude_code_config():
    """Generar configuración para Claude Code con Bedrock"""
    config = {
        "provider": "bedrock",
        "model": "anthropic.claude-3-5-sonnet-20241022-v2:0",
        "region": "us-east-1",
        "profile": "bedrock"
    }
    return config


def generate_aider_config():
    """Generar configuración para Aider con Bedrock"""
    config = {
        "model": "bedrock/anthropic.claude-3-5-sonnet-20241022-v2:0",
        "aws-region": "us-east-1",
        "aws-profile": "bedrock"
    }
    return config


def save_bedrock_config(config_dir: Path):
    """Guardar configuraciones para Claude Code y Aider"""
    config_dir.mkdir(parents=True, exist_ok=True)

    # Guardar config de Claude Code
    claude_config = generate_claude_code_config()
    claude_config_path = config_dir / "claude-code-bedrock.json"
    with open(claude_config_path, "w") as f:
        json.dump(claude_config, f, indent=2)
    print(f"\n✅ Configuración Claude Code guardada: {claude_config_path}")

    # Guardar config de Aider
    aider_config = generate_aider_config()
    aider_config_path = config_dir / "aider-bedrock.json"
    with open(aider_config_path, "w") as f:
        json.dump(aider_config, f, indent=2)
    print(f"✅ Configuración Aider guardada: {aider_config_path}")

    return claude_config_path, aider_config_path


def create_env_file():
    """Crear archivo .env con variables de Bedrock"""
    env_path = Path(".env.bedrock")

    env_content = """# Bedrock Configuration for Claude Code and Aider
# Generated by bedrock_setup.py

# AWS Bedrock Settings
AWS_REGION=us-east-1
AWS_PROFILE=bedrock

# Claude Code Settings
CLAUDE_CODE_PROVIDER=bedrock
CLAUDE_CODE_MODEL=anthropic.claude-3-5-sonnet-20241022-v2:0

# Aider Settings
AIDER_MODEL=bedrock/anthropic.claude-3-5-sonnet-20241022-v2:0
AIDER_AWS_REGION=us-east-1
AIDER_AWS_PROFILE=bedrock
"""

    with open(env_path, "w") as f:
        f.write(env_content)

    print(f"\n✅ Variables de entorno guardadas: {env_path}")
    print("\n📝 Para usar en PowerShell:")
    print("   $env:AWS_REGION='us-east-1'")
    print("   $env:AWS_PROFILE='bedrock'")
    print("   $env:CLAUDE_CODE_PROVIDER='bedrock'")
    return env_path


def main():
    """Ejecutar setup completo de Bedrock"""
    print("=" * 70)
    print("🚀 BEDROCK SETUP FOR CLAUDE CODE & AIDER")
    print("=" * 70)

    # Paso 1: Verificar credenciales
    print("\n[1/3] Verificando credenciales AWS...")
    if not check_aws_credentials():
        return 1

    # Paso 2: Verificar acceso a Bedrock
    print("\n[2/3] Verificando acceso a Bedrock...")
    if not check_bedrock_access():
        return 1

    # Paso 3: Guardar configuraciones
    print("\n[3/3] Guardando configuraciones...")
    config_dir = Path(".cde/bedrock-config")
    try:
        claude_config, aider_config = save_bedrock_config(config_dir)
        create_env_file()
    except Exception as e:
        print(f"❌ Error guardando configuraciones: {e}")
        return 1

    print("\n" + "=" * 70)
    print("✅ BEDROCK SETUP COMPLETADO")
    print("=" * 70)
    print("\n📋 Próximos pasos:")
    print("   1. Claude Code:")
    print("      claude-code run --provider bedrock \\")
    print("        --model anthropic.claude-3-5-sonnet-20241022-v2:0 \\")
    print("        --prompt 'Your task here'")
    print("\n   2. Aider:")
    print("      aider --model bedrock/anthropic.claude-3-5-sonnet-20241022-v2:0")
    print("\n   3. O usa las variables de entorno de .env.bedrock")

    return 0


if __name__ == "__main__":
    sys.exit(main())
